"""empty message

Revision ID: 9f5a49894627
Revises: bcea4d199dc1
Create Date: 2017-03-13 19:50:10.787302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5a49894627'
down_revision = 'bcea4d199dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('userid', sa.Integer(), nullable=False))
    op.add_column('profiles', sa.Column('username', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['userid'])
    op.drop_column('profiles', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'username')
    op.drop_column('profiles', 'userid')
    # ### end Alembic commands ###
